### ISSUE TITLE
Write tests, task 2.

### ISSUE THREAD

**Issue by Carnoustie** [GroupFiveSW/Algorithms#16]
Writing tests to improve code coverage, Task 2.

- [x] #17
- [x] #18
- [x] #27 
- [x] #28

**Comment by gustafvh** [comment]
After discussing in group the following tests have been assigned:

- @Carnoustie Writes tests for `lcs()` 
- @gustafvh Writes tests for `lcs()` (Additional tests for that function)
- @elibon99 Writes tests for `bfs()` 
- @Klako Writes for `reduce()` (ChineseTheorem)
