### ISSUE TITLE
Write four new tests per group member that improved code coverage (3.5.2.3) (Pass + criterion).

### ISSUE THREAD

**Issue by Carnoustie** [GroupFiveSW/Algorithms#18]
- [x] #24
- [x] #29 
- [x] #30 
- [x] #31 
- [x] #32

**Comment by gustafvh** [comment]
After discussing in group the following tests have been assigned:

- @Carnoustie Writes tests for `lcs()` 
- @gustafvh Writes tests for `lcs()` (Additional tests for that function)
- @elibon99 Writes tests for `bfs()` 
- @Klako Writes for `reduce()` (ChineseTheorem)
