### ISSUE TITLE
Self Assesment, task 4.

### ISSUE THREAD

**Issue by Carnoustie** [GroupFiveSW/Algorithms#19]
Assess your way of working with respect to guidelines found in page 58 of the essence standard by evaluating the checklist outlined on page 60.

**Comment by gustafvh** [comment]
Draft written and can be found here for those who wants to have a read to make sure they agree with whats been written: https://docs.google.com/document/d/1bt9GIrMK8Onisi5SNo1qF5o6E88D0EX2Kfyqa3HVL58/edit#
