### ISSUE TITLE
Part 2.1: Run regression tests and save test logs for repo 

### ISSUE THREAD

**Issue by gustafvh** [GroupFiveSW/Algorithms#37]
Run the existing regression tests; make sure they succeed. If any tests fail, check if they may interfere
with your task. Keep copies of the test logs. If you there is a problem with the existing tests that
interferes with your task, document that as a new issue (in the issue tracker), and either try to resolve
it, or change your task to a different issue, perhaps in a different project.

**Comment by Klako** [comment]
duplicate of #39
