### ISSUE TITLE
Run existing regressions tests and keep copies of test logs

### ISSUE THREAD

**Issue by elibon99** [GroupFiveSW/Algorithms#39]
Run the existing regressions tests; make sure they succeed. If any tests fail, check if they may interfere
with our issue. Keep copies of the test logs. If there is a problem with the existing tests that
interferes with our issue, document that as a new issue (in the issue tracker), and either try to resolve
it, or change your task to a different issue, perhaps in a different project.

**Comment by Klako** [comment]
All tests succeed and there will be no interference with our own implementation.
![2022-02-28_10-43-02](https://user-images.githubusercontent.com/4390016/155960845-9ec37eed-1c58-446c-ae62-8f31afdfd291.png)
