### ISSUE TITLE
Identify requirements related to our issue and create project plan for testing these requirements

### ISSUE THREAD

**Issue by elibon99** [GroupFiveSW/Algorithms#44]
Identify requirements related to our issue. If the requirements are not documented yet, try to describe them based on code reviews and existing test cases. Create a project plan for testing these requirements, and working on the issue.

**Comment by elibon99** [comment]
I have created a list of requirements for Rope (data structure) which can be found [here](https://docs.google.com/spreadsheets/d/1CHjb1iNa_pav-ySRgypskDsi5elQjVTBgGag3RQL6HE/edit?usp=sharing).

NOTE: The requirements are based upon the standard operations of a rope data structure

**Comment by Carnoustie** [comment]
Created Project Plan for testing requirements, to be found in the [report](https://docs.google.com/document/d/1fuZfs5OmAHSEE7-_Y_GGQDoY2GnvouBpUqnO2LI3ao8/edit#) under "Project Plan".

Elias identified [requirements](https://docs.google.com/spreadsheets/d/1CHjb1iNa_pav-ySRgypskDsi5elQjVTBgGag3RQL6HE/edit#gid=0) associated with supported functionality of the rope datastructure.
