### ISSUE TITLE
Implement unit tests for delete operation (REQ-4)

### ISSUE THREAD

**Issue by elibon99** [GroupFiveSW/Algorithms#63]
Implement unit test for the operation **delete** for the Rope data structure (REQ-4).

For requirements see [here](https://docs.google.com/spreadsheets/d/1CHjb1iNa_pav-ySRgypskDsi5elQjVTBgGag3RQL6HE/edit#gid=0)

**Comment by Klako** [comment]
Current tests do not cover Leaf::delete
